plugins=(git fzf aliases eza zsh-syntax-highlighting zsh-autosuggestions)

export ZSH="$HOME/.oh-my-zsh"
export EDITOR="nvim";
export SUDO_EDITOR="nvim"
export VISUAL="nvim"
export LANG="en_US.UTF-8"
export BROWSER="firefox"
export STEAMPATH="$HOME/.local/share/Steam"
export FZF_DEFAULT_COMMAND="fd"
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border"
export DOTS="$HOME/dotfiles/config"
export PATH="$PATH:$HOME/.local/bin/:$HOME/dotfiles/scripts:$HOME/dotfiles/scripts/internals:$HOME/.userpath/"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
export INPUT_METHOD=fcitx
export SOUNDS_ENABLED=true

alias mix="pavucontrol"
alias grep="rg"
alias find="fd"
alias cat="bat"
alias yazi="y"
alias mv="mv -v"
alias cp="cp -vr"
alias gt="gtrash"
alias gtp="gtrash put"
alias sr="source ~/.zshrc"
alias rm="echo 'use \"gtp\" instead'"
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"
alias mkdir="mkdir -p"
alias pk="pkill -9 -f"
alias svcu="systemctl --user"
alias svc="sudo systemctl"
alias viflake="nvim flake.nix"
alias record="wf-recorder"
alias vide="neovide"
alias vi="nvim"
alias videconf="EDITOR=neovide; viconf"
alias mkexe="chmod +x"
alias k9="kill -9"
alias gcomm="gitcommit_sfx"
alias gpush="gitpush_sfx"
alias shortdate="date '+%m-%d-%y'"

setopt APPEND_HISTORY     # Append history to the history file (don't overwrite)
setopt INC_APPEND_HISTORY # Append to the history file incrementally
setopt SHARE_HISTORY      # Share history between all zsh sessions

setopt CORRECT
setopt NO_NOMATCH
setopt LIST_PACKED
setopt ALWAYS_TO_END
setopt GLOB_COMPLETE
setopt COMPLETE_ALIASES
setopt COMPLETE_IN_WORD
setopt AUTO_CD
setopt AUTO_CONTINUE
setopt LONG_LIST_JOBS
setopt HIST_VERIFY
setopt SHARE_HISTORY
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt EXTENDED_GLOB
setopt TRANSIENT_RPROMPT
setopt INTERACTIVE_COMMENTS

autoload -U compinit     # completion
autoload -U terminfo     # terminfo keys
zmodload -i zsh/complist # menu completion
autoload -U promptinit   # prompt

autoload -U up-line-or-beginning-search; zle -N up-line-or-beginning-search
autoload -U down-line-or-beginning-search; zle -N down-line-or-beginning-search

compinit
source ~/.oh-my-zsh/custom/plugins/fzf-tab/fzf-tab.plugin.zsh
source ~/.config/zsh/custom/cmdstat/cmdstat.plugin.zsh
source $ZSH/oh-my-zsh.sh

mkcd() {
	mkdir -p "$1" && cd "$1"
}

cd() {
	local prev_sounds_enabled="$SOUNDS_ENABLED"
	export SOUNDS_ENABLED=0
	eza -1 --group-directories-first --icons "$@"
	export SOUNDS_ENABLED=$prev_sounds_enabled
	builtin cd "$@"
	playshellsound "$HOME"/dotfiles/assets/sound/cd.wav
	return 0
}

unalias ls
ls() {
	eza -1 --group-directories-first --icons "$@"
	playshellsound "$HOME"/dotfiles/assets/sound/ls.wav
	return 0
}

gitcommit_sfx() {
	output=$(git commit "$@")
	if [ -n "$output" ]; then
		playshellsound "$HOME"/dotfiles/assets/sound/gitcommit.wav
		echo "$output" | color-commit
		return 0
	else
		playshellsound "$HOME"/dotfiles/assets/sound/error.wav
		echo "$output"
		return 1
	fi
}
gitpush_sfx() {
	if git push "$@"; then
		playshellsound "$HOME"/dotfiles/assets/sound/gitpush.wav
		return 0
	else
		playshellsound "$HOME"/dotfiles/assets/sound/error.wav
		return 1
	fi
}

if [ ! -e $HOME/.zsh_history ]; then
	touch $HOME/.zsh_history
	chmod 600 $HOME/.zsh_history
fi

bindkey -v
type starship_zle-keymap-select >/dev/null || \
{
	eval "$(starship init zsh)"
}
