alias mix="pavucontrol"
alias grep="rg"
alias find="fd"
alias cat="bat"
alias yazi="y"
alias mv="mv -v"
alias cp="cp -vr"
alias gt="gtrash"
alias gtp="gtrash put"
alias sr="source ~/.zshrc"
alias rm="echo 'use \"gtp\" instead'"
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"
alias mkdir="mkdir -p"
alias pk="pkill -9 -f"
alias svcu="systemctl --user"
alias svc="sudo systemctl"
alias viflake="nvim flake.nix"
alias record="wf-recorder"
alias vide="neovide"
alias vi="$EDITOR"
alias videconf="EDITOR=neovide; viconf"
alias mkexe="chmod +x"
alias k9="kill -9"
alias gcomm="gitcommit_sfx"
alias gpush="gitpush_sfx"
alias shortdate="date '+%m-%d-%y'"
alias suvi="sudoedit"
alias suvide="EDITOR=neovide; suvi"

echo sourced aliases
