path = "/home/pagedmov/dotfiles/config/nvim/lua/plugins/base16.lua"
content = '''
return {
	{
		"RRethy/nvim-base16",
		lazy = false,
		priority = 1000,
		config = function()
			require('base16-colorscheme').setup({
          base00 = "${{base01}}",
          base01 = "${{base00}}",
          base02 = "${{base02}}",
          base03 = "${{base03}}",
          base04 = "${{base04}}",
          base05 = "${{base05}}",
          base06 = "${{base06}}",
          base07 = "${{base07}}",
          base08 = "${{base08}}",
          base09 = "${{base09}}",
          base0A = "${{base0A}}",
          base0B = "${{base0B}}",
          base0C = "${{base0C}}",
          base0D = "${{base0D}}",
          base0E = "${{base0E}}",
          base0F = "${{base0F}}",
			})
		end
	}
}
'''
