path = "/home/pagedmov/dotfiles/config/waybar/config_horizontal"
content = '''
{
    "layer": "top",
    "position": "top",
    "mod": "dock",
    "exclusive": true,
    "passtrough": false,
    "gtk-layer-shell": true,
    "height": 0,
    "name": "horBar",

    "modules-left": [
	"clock",
	"hyprland/workspaces",
	"tray"
    ],

    "modules-center": [
    ],

    "modules-right": [
    	"cpu",
	"memory",
        "pulseaudio",
	"custom/updates",
	"network"
    ],

    "idle_inhibitor": {
    	"format": "[ {icon} ]",
	"tooltip-format-activated": "IDLE_STATUS: [ ACTIVE ]",
	"tooltip-format-deactivated": "IDLE_STATUS: [ <span color='${{red}}'>NON_ACTIVE</span> ]",
	"format-icons": {
		"activated": "ACT",
		"deactivated": "<span color='${{red}}'>XXX</span>"
	}
    },
    
    "tray": {
        "icon-size": 14,
	"show-passive-items": true,
        "spacing": 14,
	"reverse-direction": true
    },

    "memory": {
    	"interval": 20,
	"format": "MEM: [ <span color='${{selection}}'>{icon}</span> ] <span size='8pt'>{percentage}%</span>",
	"tooltip-format": "MEM_TOT\t: {total}GiB\nSWP_TOT\t: {swapTotal}GiB\n\nMEM_USD\t: {used:0.1f}GiB\nSWP_USD\t: {swapUsed:0.1f}GiB",
	"format-icons": ["░░░░░░░░", "█░░░░░░░", "██░░░░░░", "███░░░░░", "████░░░░", "█████░░░", "██████░░", "<span color='${{red}}'>!!!!!!!!</span>", "<span color='${{red}}'>CRITICAL</span>"]
    },

		"hyprland/workspaces": {
			"active-only": false,
			"format": "{icon}",
			"format-icons": {
				"1": "1",
				"2": "2",
				"3": "3",
				"4": "4",
				"5": "5",
				"6": "6",
				"7": "7",
				"8": "8",
				"9": "9",
				"10": "10",
				"11": "11",
				"12": "12",
				"13": "13",
				"14": "14",
				"15": "15",
				"16": "16",
				"17": "17",
				"18": "18",
				"19": "19",
				"20": "20"
			},
			"persistent-workspaces": {
				"HDMI-A-1": [1,2,3],
				"DP-1": [4,5,6]
			}
		},

    "cpu": {
    	"interval": 1,
	"format": "CPU: [ <span color='${{selection}}'>{icon}</span> ] <span size='8pt'>{usage}%</span>",
	"tooltip": true,
	"format-icons": ["░░░░░░░░", "█░░░░░░░", "██░░░░░░", "███░░░░░", "████░░░░", "█████░░░", "██████░░", "<span color='${{selection}}'>!!!!!!!!</span>", "<span color='${{selection}}'>CRITICAL</span>"]
    },

    "clock": {
        "format": "[ CLK: {:%H.%M <span size='8pt'> %a %b %d</span>} ]",
        "tooltip-format": "<tt>{calendar}</tt>",
		"calendar": {
			"mode": "month",
			"weeks-pos": "",
			"on-scroll": 1,
			"format": {
				"months": "<span size='16pt'><b>CAL: {}\n</b></span>", 
				"days": "<span size='16pt'><b>{}</b></span>", 
				"weeks": "<span size='16pt'><b>{}</b></span>", 
				"weekdays": "<span size='16pt'><b>{}</b></span>", 
				"today": "<span color='${{fg}}'><b><u>{}</u></b></span>"
		}
		},
	"actions": {
		"on-scroll-up": "shift_down",
		"on-scroll-down": "shift_up"
	}
    },

    "pulseaudio": {
        "format": "VOL: [ <span color='${{selection}}'>{icon}</span> ] <span size='8pt'>{volume}%</span>",
        "tooltip": true,
	"tooltip-format": "DEVICE: {desc}",
        "format-muted": "VOL: <span color='${{red}}'>[ XXXXXXXX ] <span size='8pt'>{volume}%</span></span>",
        "on-click": "if [ $(pamixer --get-mute) == true ]; then pamixer --unmute; else pamixer --mute; fi",
        "on-scroll-up": "pamixer -i 2",
        "on-scroll-down": "pamixer -d 2",
        "scroll-step": 2,
	"reverse-scrolling": true,
	"format-icons": ["░░░░░░░░", "█░░░░░░░", "██░░░░░░", "███░░░░░", "████░░░░", "█████░░░", "██████░░", "███████░", "████████"]
    },

    "network": {
	"format-wifi": "[ <span color='${{green}}'>ONLINE</span> ]",
	"format-ethernet": "[ <span color='${{green}}'>ONLINE</span> ]",
	"tooltip-format-wifi": "ESSID\t: {essid}\nSTRNGTH\t: {signaldBm}\n\nADDRESS\t: {ipaddr}\nGATE\t: {gwaddr}\nMASK\t: {netmask} | {cidr}",
	"tooltip-format-ethernet": "IFNAME: {ifname}\nADDRESS: {ipaddr}",
	"format-disconnected": "[ <span color='${{red}}'>XXXXXX</span> ]",
	"on-click": "nm-connection-editor"
    },

    "battery": {
    	"states": {
		"warning": 20,
		"critical": 15
	},
	"format": "BAT: [ {icon} ] <span size='8pt'>{capacity}%</span>",
	"interval": 5,
	"format-charging": "BAT: [ {icon} ] <span size='8pt'>CHRG</span>",
	"format-plugged": "BAT: [ {icon} ] <span size='8pt'>PLUG</span>",
	"tooltip-format": "BATTERY: {power}W\nSTATUS: {timeTo}\nCYCLES: {cycles}\nHEALTH: {health}",
	"format-icons": ["<span color='${{red}}'>CRITICAL", "<span color='${{red}}'>!!!!!!!!</span>", "██░░░░░░", "███░░░░░", "████░░░░", "█████░░░", "██████░░", "███████░", "████████"]
    },

    "custom/updates": {
    	"format": "{} [ {icon} ]",
	"return-type": "json",
	"format-icons": {
		"has-updates": "<span color='${{red}}'>!!!!!!</span>",
		"updated": "<span color='${{green}}'>UPDATE</span>"
	},
	"exec-if": "which waybar-module-pacman-updates",
	"exec": "waybar-module-pacman-updates --no-zero-output"
    }
}
'''
