path = "/home/pagedmov/dotfiles/config/waybar/stylehor.css"
content = '''
* {
    font-size: 14px;
    border: none;
    font-family: EnvyCodeR Nerd Font Mono;
    font-weight: Bold;
    min-height: 0;
    border-radius: 0px;
    padding: 2px;
}

window#waybar {
    color: ${{fg}};
    background: ${{bg}};
}

tooltip {
    background: ${{bg}};
}

#workspaces button {
    color: ${{fg}};
}

#workspaces button.active {
    color: ${{selection}};
    background: ${{bg}};
}

#workspaces button.focused {
    color: #9D9140;
    background: ${{bg}};
}

#workspaces button.urgent {
    color: ${{fg}};
    background: ${{bg}};
}

#workspaces button:hover {
    background: ${{fg}};
    color: ${{bg}};
}

#custom-language,
#custom-updates,
#custom-caffeine,
#custom-weather,
#window,
#clock,
#battery,
#pulseaudio,
#network,
#workspaces,
#tray,
#cpu,
#backlight {
    padding: 0px 10px;
    margin: 0px;
}

#tray {
    margin-right: 10px;
}

#workspaces {
    color: ${{fg}};
}

#window {
    color: ${{fg}};
}

.verBar#clock {
    color: #C4E969;
}

.horBar#clock {
    color: ${{fg}};
}

#network {
    color: ${{fg}};
}

#pulseaudio {
    color: ${{fg}};
}

#pulseaudio.microphone {
    color: ${{fg}};
}

#battery {
    color: ${{fg}};
}

#battery.warning:not(.charging) {
    color: ${{yellow}};
}

#battery.critical:not(.charging) {
    color: ${{red}};
}
'''
